[package]
name = "sdkwork-api-skills-assembly"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Generated API assembly for sdkwork-skills application HTTP plane."

[lib]
name = "sdkwork_api_skills_assembly"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
tokio.workspace = true
sdkwork-intelligence-skills-repository-sqlx = { path = "../sdkwork-intelligence-skills-repository-sqlx" }
sdkwork-intelligence-skills-service = { path = "../sdkwork-intelligence-skills-service" }
sdkwork-routes-skills-app-api = { path = "../sdkwork-routes-skills-app-api" }
sdkwork-routes-skills-backend-api = { path = "../sdkwork-routes-skills-backend-api" }
